server:
  port: 8002
user:
  userservice:
    url: "http://localhost:8001/user/"
spring:
  application:
    name: micro-provider-movieservice
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka,http://peer2:8762/eureka
  instance:
    prefer-ip-address: true

